// Expo's ambient types (process.env.EXPO_PUBLIC_*, asset modules, ...).
// `expo-env.d.ts` is generated by `expo start` and git-ignored; this committed reference keeps
// `tsc --noEmit` and ESLint type-aware rules working on a fresh clone and in CI.
/// <reference types="expo/types" />
